### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by TiagoHA** [emanuelgsouza/tcc-biblioteca#4]
O package.json está com uma virgula desnecessária no final.

`  "dependencies": {
    "bulma": "^0.2.3",
    "font-awesome": "^4.7.0",
    "pouchdb": "^6.1.1",
    "pouchdb-browser": "^6.1.1",
    "pouchdb-find": "^0.10.4",
    "pouchdb-replication-stream": "^1.2.9",
  }`

**Comment by emanuelgsouza** [comment]
Valeu cara, irei corrigir. Thanks! Aliás, eu preciso atualizar o projeto :)
